---

- name: rhevm_import | enable non-interactive rhevm-image-uploader
  lineinfile: dest={{item}} state=present regexp='^passwd=' line='passwd={{auth_pass}}'
  with_items:
    - /etc/rhevm/imageuploader.conf
  when: ansible_distribution == 'RedHat'

- name: rhevm_import | enable non-interactive rhevm-image-uploader
  lineinfile: dest={{item}} state=present regexp='^passwd=' line='passwd={{auth_pass}}'
  with_items:
    - /etc/ovirt-engine/imageuploader.conf
  when: ansible_distribution == 'Fedora'

- name: rhevm_import | download appliance
  get_url: url={{appliance_url}} dest=/tmp mode=0640
  register: appliance_file

- name: rhevm_import | determine image name
  shell: basename {{appliance_file.dest}} | sed 's|\.\w*$||'
  register: appliance_name

- name: rhevm_import | determine if template already imported
  local_action: shell files/ovirt-cli.py --url https://{{host_fqdn}}/api --username {{auth_user}} --password {{auth_pass}} storagedomains.templates.list | grep {{appliance_name.stdout}}
  register: is_image_uploaded
  ignore_errors: yes

- name: rhevm_import | rhevm-image-uploader
  shell: $ovirt_image_uploader -v -e {{export_domain}} --name {{appliance_name.stdout}} upload {{appliance_file.dest}}
  when: is_image_uploaded|failed

- name: rhevm_import | wait for template upload to complete
  local_action: shell MAX_TRIES=60 ; TRY=1 ; until files/ovirt-cli.py --url https://{{host_fqdn}}/api --username {{auth_user}} --password {{auth_pass}} storagedomains.templates.list | grep {{appliance_name.stdout}} ; do [ $TRY -gt $MAX_TRIES ] && exit 1 ; sleep 5; TRY=$((TRY+1)) ; done
  register: is_image_available
  ignore_errors: yes

- name: rhevm_import | storagedomains.template.import
  local_action: shell files/ovirt-cli.py --url https://{{host_fqdn}}/api --username {{auth_user}} --password {{auth_pass}} storagedomains.templates.import --name {{appliance_name.stdout}}
  when: is_image_available|success
